"""Add Games Played to player

Revision ID: 6dafaf0229f7
Revises: cccd78c17393
Create Date: 2023-09-13 17:41:01.340551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dafaf0229f7'
down_revision = 'cccd78c17393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('games_played', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('games_played')

    # ### end Alembic commands ###
