"""Add Fixed Table information

Revision ID: 01b9a8aae1b0
Revises: cccd78c17393
Create Date: 2023-10-14 16:46:28.377601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b9a8aae1b0'
down_revision = 'cccd78c17393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fixed_table', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('table_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('table_number')
        batch_op.drop_column('fixed_table')

    # ### end Alembic commands ###
