"""empty message

Revision ID: 0e24f9aa6058
Revises: b797a1be4ea7
Create Date: 2024-01-12 23:29:53.203497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e24f9aa6058'
down_revision = 'b797a1be4ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decklist')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tournament_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('side', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cards', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_legal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name='decklist_player_id_fkey'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], name='decklist_tournament_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='decklist_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='decklist_pkey')
    )
    # ### end Alembic commands ###
