"""empty message

Revision ID: b797a1be4ea7
Revises: b605904e0eec
Create Date: 2024-01-12 23:08:21.696847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b797a1be4ea7'
down_revision = 'b605904e0eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reveal_cut_decklists', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reveal_decklists', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('reveal_decklists')
        batch_op.drop_column('reveal_cut_decklists')

    # ### end Alembic commands ###
