"""updating to allow required login

Revision ID: 53c86fa7fe75
Revises: 0e24f9aa6058
Create Date: 2024-02-09 15:04:45.614037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c86fa7fe75'
down_revision = '0e24f9aa6058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['uid'], ['id'])

    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('require_login', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('require_login')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
