"""fix misspelling

Revision ID: e3aff946caa0
Revises: 53c86fa7fe75
Create Date: 2025-06-25 14:24:12.472133

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e3aff946caa0"
down_revision = "53c86fa7fe75"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.alter_column(
            column_name="recieved_bye",
            new_column_name="received_bye",
            existing_type=sa.BOOLEAN(),
            nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player", schema=None) as batch_op:
        batch_op.alter_column(
            new_column_name="recieved_bye",
            column_name="received_bye",
            existing_type=sa.BOOLEAN(),
            nullable=True,
        )

    # ### end Alembic commands ###
