"""initial commit

Revision ID: 7f96dc416dd2
Revises: 
Create Date: 2023-04-17 17:12:27.400835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f96dc416dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('admin_rights', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cut',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('rnd', sa.Integer(), nullable=True),
    sa.Column('num_players', sa.Integer(), nullable=True),
    sa.Column('double_elim', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tid'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('corp', sa.String(), nullable=True),
    sa.Column('runner', sa.String(), nullable=True),
    sa.Column('corp_deck', sa.Text(), nullable=True),
    sa.Column('runner_deck', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('recieved_bye', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('sos', sa.Numeric(), nullable=True),
    sa.Column('esos', sa.Numeric(), nullable=True),
    sa.Column('is_bye', sa.Boolean(), nullable=True),
    sa.Column('first_round_bye', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tid'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cut_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('cut_id', sa.Integer(), nullable=True),
    sa.Column('elim_round', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cut_id'], ['cut.id'], name='cut_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cut_id', 'seed', name='cut_player_seed_unique')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tid', sa.Integer(), nullable=True),
    sa.Column('rnd', sa.Integer(), nullable=True),
    sa.Column('corp_player_id', sa.Integer(), nullable=True),
    sa.Column('runner_player_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('concluded', sa.Boolean(), nullable=True),
    sa.Column('is_bye', sa.Boolean(), nullable=True),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corp_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['runner_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['tid'], ['tournament.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elim_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cut_id', sa.Integer(), nullable=True),
    sa.Column('rnd', sa.Integer(), nullable=True),
    sa.Column('higher_seed_id', sa.Integer(), nullable=True),
    sa.Column('lower_seed_id', sa.Integer(), nullable=True),
    sa.Column('corp_player_id', sa.Integer(), nullable=True),
    sa.Column('runner_player_id', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('concluded', sa.Boolean(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('loser_id', sa.Integer(), nullable=True),
    sa.Column('table_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corp_player_id'], ['cut_player.id'], ),
    sa.ForeignKeyConstraint(['cut_id'], ['cut.id'], name='cut_id_fk', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['higher_seed_id'], ['cut_player.id'], ),
    sa.ForeignKeyConstraint(['loser_id'], ['cut_player.id'], ),
    sa.ForeignKeyConstraint(['lower_seed_id'], ['cut_player.id'], ),
    sa.ForeignKeyConstraint(['runner_player_id'], ['cut_player.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['cut_player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elim_match')
    op.drop_table('match')
    op.drop_table('cut_player')
    op.drop_table('player')
    op.drop_table('cut')
    op.drop_table('tournament')
    op.drop_table('user')
    # ### end Alembic commands ###
