"""compressing multiple tournaments into one

Revision ID: cccd78c17393
Revises: a5ce4b6da5bb
Create Date: 2023-08-25 18:29:58.224940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cccd78c17393'
down_revision = 'a5ce4b6da5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('to_pref')
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_self_registration', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_self_results_report', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('visible', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament', schema=None) as batch_op:
        batch_op.drop_column('visible')
        batch_op.drop_column('allow_self_results_report')
        batch_op.drop_column('allow_self_registration')

    op.create_table('to_pref',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allow_self_registration', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('allow_self_results_report', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tid'], ['tournament.id'], name='to_pref_tid_fkey'),
    sa.PrimaryKeyConstraint('id', name='to_pref_pkey')
    )
    # ### end Alembic commands ###
